// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: node-controller.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NodeControllerClient is the client API for NodeController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeControllerClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type nodeControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeControllerClient(cc grpc.ClientConnInterface) NodeControllerClient {
	return &nodeControllerClient{cc}
}

func (c *nodeControllerClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/NodeController/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeControllerServer is the server API for NodeController service.
// All implementations must embed UnimplementedNodeControllerServer
// for forward compatibility
type NodeControllerServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedNodeControllerServer()
}

// UnimplementedNodeControllerServer must be embedded to have forward compatible implementations.
type UnimplementedNodeControllerServer struct {
}

func (UnimplementedNodeControllerServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedNodeControllerServer) mustEmbedUnimplementedNodeControllerServer() {}

// UnsafeNodeControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeControllerServer will
// result in compilation errors.
type UnsafeNodeControllerServer interface {
	mustEmbedUnimplementedNodeControllerServer()
}

func RegisterNodeControllerServer(s grpc.ServiceRegistrar, srv NodeControllerServer) {
	s.RegisterService(&NodeController_ServiceDesc, srv)
}

func _NodeController_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControllerServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NodeController/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControllerServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeController_ServiceDesc is the grpc.ServiceDesc for NodeController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "NodeController",
	HandlerType: (*NodeControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _NodeController_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node-controller.proto",
}
